/**
 * Agent 9 — HR Notifier Test Suite
 *
 * Tests:
 *   A. Integration/DB Tests (requires active Supabase session):
 *      A1. Call notify_hr() directly with delivered = false / missing credentials
 *      A2. Verify row is inserted in notifications_log with correct hr_user_id, event_type, message, and delivered status
 */

import { notify_hr } from '../services/notificationService';
import { supabase } from '../lib/supabase';
import { getCurrentUser } from '../services/authService';

function assert(condition: boolean, message: string): void {
  if (!condition) throw new Error(`❌ ASSERTION FAILED: ${message}`);
}

async function testNotificationLogging(): Promise<void> {
  console.log('  A1. Trigger notify_hr and verify DB log');
  const hr_user_id = await getCurrentUser();

  const eventType = 'test_notification_event';
  const msg = 'Test notification message generated by Antigravity test suite.';

  // Trigger notification
  const sent = await notify_hr(hr_user_id, eventType, msg);
  console.log('    notify_hr returned delivered status:', sent);

  // Retrieve the log from DB
  const { data: log, error } = await supabase
    .from('notifications_log')
    .select('*')
    .eq('hr_user_id', hr_user_id)
    .eq('event_type', eventType)
    .order('created_at', { ascending: false })
    .limit(1)
    .single();

  if (error || !log) {
    throw new Error(`Failed to find logged notification in DB: ${error?.message}`);
  }

  assert(log.message === msg, 'Logged message mismatch');
  assert(log.delivered === sent, 'Logged delivered status mismatch');
  console.log('    ✅ DB log found and fields verified.');

  // Clean up
  console.log('    Cleaning up log row…');
  await supabase.from('notifications_log').delete().eq('id', log.id);
  console.log('    ✅ Cleaned up log.');
}

export async function runAgent9Tests(): Promise<void> {
  console.log('═══════════════════════════════════════════════════════════');
  console.log('  Agent 9 (HR Notifier) Test Suite');
  console.log('═══════════════════════════════════════════════════════════');

  try {
    await testNotificationLogging();
    
    console.log('\n═══════════════════════════════════════════════════════════');
    console.log('  ✅ Agent 9 tests completed successfully!');
    console.log('═══════════════════════════════════════════════════════════\n');
  } catch (err: any) {
    console.error('\n❌ Tests failed:', err.message);
  }
}

if (typeof window === 'undefined') {
  runAgent9Tests().catch((e) => {
    console.error('Test suite failed:', e.message);
    process.exit(1);
  });
}
